spring:
  application:
    name: wildpulse-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/wildpulse_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  messages:
    basename: classpath:validation.messages

logging:
  level:
    root: WARN
    com:
      wildpulse: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %level - %logger{36} - %msg%n"