name: wp-quality-checks
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  wp-quality-checks:
    name: Wildpulse quality checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew
      - name: Run clean and build
        run: ./gradlew clean build --refresh-dependencies
      - name: Run spotless check
        run: ./gradlew spotlessCheck
      - name: Run unit tests
        run: ./gradlew clean test
      - name: Generate JaCoCo test report
        run: ./gradlew jacocoTestReport
      - name: Fail PR if overall coverage is less than 95%
        if: ${{ steps.jacoco.outputs.coverage-overall < 95.0 }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Overall coverage is less than 95%!')
                  core.setFailed('Coverage threshold not met.')
