name: wildpulse-quality-checks-backend-coverage

on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main

jobs:
  jacoco:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Run Tests with Jacoco
        run: mvn clean verify
      - name: Check Jacoco Coverage
        run: |
          COVERAGE=$(mvn jacoco:report | grep -oP '(?<=Total instruction coverage: )\d+.\d+')
          if (( $(echo "$COVERAGE < 90.0" | bc -l) )); then
            echo "Code coverage is below 90%. Coverage: $COVERAGE%"
            exit 1
          fi